apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybox
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mybox
  template:
    metadata:
      labels:
        run: mybox
    spec:
      containers:
        # ecr Image
        - image: 776945434852.dkr.ecr.ap-northeast-2.amazonaws.com/repo:latest
          name: mybox
          ports:
            - containerPort: 8080